# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :restore_dependencies do
    cocoapods(
      repo_update: true,
      use_bundle_exec: true
    )

    if ENV["POINTSDK_REF"]
      puts("🌊 using upstream artifacts")

      Dir.chdir("..") do
        sh("touch artifacts.zip")
        sh("curl --header 'JOB-TOKEN: #{ENV["CI_JOB_TOKEN"]}' -L 'https://gitlab.com/api/v4/projects/14702395/jobs/artifacts/#{ENV["POINTSDK_REF"]}/download?job=framework-xcode-default' >> artifacts.zip")
        sh("unzip artifacts.zip")
      end

      copy_artifacts(
        target_path: "Carthage/Build/iOS",
        artifacts: ["build/artifacts/framework-Release/Xcode**/BDPointSDK.framework"]
      )
    end
  end

  desc 'Executes UI tests for the project. Parameters: xcode, project. e.g. xcode:"11.0" app:"MyApp"'
  lane :ui_test do |options|
    xcode = options[:xcode]
    xcversion(version: "~> #{xcode}")

    restore_dependencies

    app = options[:app]
    scan(
      workspace: "PointSDK-MinimalIntegrationExample-iOS.xcworkspace",
      scheme: app
    )
  end
end
